spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/docker_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
        username: root
        password: ${MYSQLPASS:}
        tomcat:
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            validation-query: SELECT 1

    jpa:
#        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true

init:
    username: "Pepi"
    message: "${MESSAGE:hello from application.yml!}"