version: "3"
services:
    db:
        image: mysql:8
        container_name: mysql
        ports:
            - 3307:3306
        command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin' ]
        networks:
            - docker3net
#        restart: always
        environment:
#            - MYSQL_ALLOW_EMPTY_PASSWORD=1
            - MYSQL_INITDB_SKIP_TZINFO=1
            - MYSQL_DATABASE=docker_db
            - MYSQL_ROOT_PASSWORD=1234

    myapp:
        image: deianov/docker3:latest
        container_name: docker3
        ports:
            - 8080:8080
        networks:
            - docker3net
        depends_on:
            - db
        environment:
            - MYSQLHOST=db
            - MYSQLPORT=3306
            - MYSQLPASS=1234

networks:
    docker3net: